apiVersion: v1
kind: Service
metadata:
  name: svc-cache
  namespace: app
spec:
  selector:
    app: cache
  ports:
    - name: multitool-http
      protocol: TCP
      port: 8090
      targetPort: 8090