apiVersion: v1
kind: Service
metadata:
  name: svc-back
  namespace: app
spec:
  selector:
    app: back
  ports:
    - name: multitool-http
      protocol: TCP
      port: 8080
      targetPort: 8080