apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - name: nginx
    protocol: TCP
    port: 80
  - name: https-port
    port: 11443
    protocol: TCP
  - name: http-port
    port: 1180
    protocol: TCP  