apiVersion: v1
kind: Pod
metadata:
  name: nginxpod
  labels:
    app: nginx
spec:
  containers:
  - name: network
    image: wbitt/network-multitool
    env:
    - name: HTTP_PORT
      value: "1180"
    ports:
    - containerPort: 1180
      name: http-port
