apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-busybox-deployment-nfs
  labels:
    app: nfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-box
  template:
    metadata:
      labels:
        app: multi-box
    spec:
      containers:
        - name: network-multitool
          image: wbitt/network-multitool
          env:
          - name: http-port
            value: "1180"
          - name: HTTPS_PORT
            value: "11443"
          ports:
          - containerPort: 1180
            name: http-port
          - containerPort: 11443
            name: https-port
          volumeMounts:
            - name: nfs-storage
              mountPath: /data
        - name: busybox-container
          image: busybox
          command: ["/bin/sh", "-c"]
          args: ["while true; do echo $(date '+%Y-%m-%d %H:%M:%S')
 >> /data/log.txt; sleep 5; done"]
          volumeMounts:
            - name: nfs-storage
              mountPath: /data
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: my-pvc